=== KevsCha/FP_Daw-Dam/First_Year/DA1D1A Lenguajes de marcas/XML/ejercicios 3/ej2New.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="musicos">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="musico" maxOccurs="unbounded">
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="musico">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="nombre" type="xs:string" />
				<xs:element name="apodo" type="xs:string" minOccurs="0" />
				<xs:element name="fechaNacimiento" type="xs:string" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== KevsCha/FP_Daw-Dam/First_Year/DA1D1A Lenguajes de marcas/XML/ejercicios 3/ej2New.xml
<?xml version="1.0" encoding="UTF-8" ?>
<musicos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="ej2New.xsd">
    <musico>
        <nombre>Antonio Vivaldi</nombre>
        <apodo>El cura pelirrojillo</apodo>
        <fechaNacimiento>1678-03-04</fechaNacimiento>
    </musico>
    <musico>
        <nombre>Johann Sebastian Bach</nombre>
        <fechaNacimiento>1685-03-21</fechaNacimiento>
    </musico>
</musicos>
