=== KevsCha/FP_Daw-Dam/First_Year/DA1D1A Lenguajes de marcas/XML/ejercicios 3/ej4New.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="ejercito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tierra" maxOccurs="unbounded">
				</xs:element>
				<xs:element ref="aire">
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
    <xs:element name="tierra">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="tanques" type="xs:integer" />
                <xs:element name="soldados" type="xs:integer" />
            </xs:sequence>
        </xs:complexType>
	</xs:element>
    <xs:element name="aire">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="aviones" type="xs:integer" />
                <xs:element name="soldados" type="xs:integer" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== KevsCha/FP_Daw-Dam/First_Year/DA1D1A Lenguajes de marcas/XML/ejercicios 3/ej4New.xml
<?xml version="1.0" encoding="UTF-8"?>
<ejercito xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="ej4New.xsd">
    <tierra>
        <tanques>150</tanques>
        <soldados>58</soldados>
    </tierra>
    <tierra>
        <tanques>52</tanques>
        <soldados>99</soldados>
    </tierra>
    <aire>
        <aviones>41</aviones>
        <soldados>62</soldados>
    </aire>
</ejercito>
